on: release
name: Build binaries

jobs:
  release:
    name: ${{ matrix.binaries }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binaries: [release-linux-386, release-linux-amd64, release-darwin-386, release-darwin-amd64, release-windows-386, release-windows-amd64]
    steps:
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ matrix.binaries }}
          seperator: '-'
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ steps.split.outputs._2 }}
          GOOS: ${{ steps.split.outputs._1 }}
      - name: Upload to Docker 
        uses: docker/build-push-action@v1
        with:
          repository: hugomd/cloudflare-ddns
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true

